### PR TITLE
Remove non-essential files from npm package

### PR DESCRIPTION
**Pull request by jorrit**
LICENSE and README files are included by default.

### CODE REVIEW

**Comment by tkellen** [comment]
Is there a particular problem you're trying to solve with this? I'm happy to land if you can explain what it is. I won't be cutting a release just for this, though!

**Comment by jorrit** [comment]
It's not solving a big problem, so an immediate release is not necessary at all. The current situation is that together with the main getobject code the tests, travis config and development files are installed when getobject is in the dependency tree of my project.

**Comment by jorrit** [comment]
Thanks!

**Comment by tkellen** [comment]
n/p!

**Pull request merged**
